### ISSUE TITLE
error parse bytes

### ISSUE THREAD

**Issue by IvanKirpichnikov** [Vizonex/Winloop#32]
```
ERROR:asyncio:Unhandled exception in event loop
Traceback (most recent call last):
  File "winloop\dns.pyx", line 448, in winloop.loop.__on_addrinfo_resolved
  File "winloop\errors.pyx", line 72, in winloop.loop.convert_error
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdd in position 0: invalid continuation byte
```

the error appears when I use winloop together in psycopg[binary] version 3.2.1

**Comment by IvanKirpichnikov** [comment]
it was a problem on my part

**Comment by monosans** [comment]
Hi, @IvanKirpichnikov! How did you fix it?

**Comment by IvanKirpichnikov** [comment]
> Привет, @IvanKirpichnikov! Как вы это исправили?

Привет. Ни как. Я думал, что проблема на моей стороне, но спустя время понял, что это не на моей стороне

**Comment by IvanKirpichnikov** [comment]
> Reopen the issue please

done

**Comment by Vizonex** [comment]
@IvanKirpichnikov Sorry for a year of waiting I may have come up with a solution.
```cython
msg = system.gai_strerror(sock_err).decode('utf-8', errors="surrogatescape")
```
do you think surrogateescape will pass 0xdd?

**Comment by IvanKirpichnikov** [comment]
> [@IvanKirpichnikov](https://github.com/IvanKirpichnikov) Sorry for a year of waiting I may have come up with a solution.
> 
> msg = system.gai_strerror(sock_err).decode('utf-8', errors="surrogatescape")
> 
> do you think surrogateescape will pass 0xdd?

Hi. Thanks for the solution, but I can't test it. I switched to linux =(

**Comment by IvanKirpichnikov** [comment]
I think I should have attached the MRE.

**Comment by Vizonex** [comment]
> I think I should have attached the MRE.
> 
> All I know is winloop==0.1.6 was used together with psycopg[binary]==3.2.1. And the problem appeared when connecting to PostgreSQL. It may have appeared when an unsuccessful attempt was made to connect to the database.

I wrote a reproducible test that should work on any os in the pull request. should also work on linux but incase I'll copy and paste that same snippet here.
```python
e = b'\xdd'
print(e.decode('utf-8',"surrogateescape"))
```
